name: Daily Weather Mining

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests requests_html pandas  # Add any other dependencies

    - name: Run the script
      run: python get_weather.py
      
    - name: Set up Git
      run: |
        git config --global user.name 'Robin Young'
        git config --global user.email 'robin@rayoung.org'

    - name: Commit and Push CSV
      run: |
        git add weather_data.csv
        git commit -m "Update weather data CSV"
        git push
