name: Daily Weather Mining

on:
  schedule:
    - cron: '0 4 * * *'  # Runs at 4 AM UTC, which is 12 PM GMT+8
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Cache Python packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the script
      run: python get_weather.py
      
    - name: Set up Git
      run: |
        git config --local user.email "59581322+rbnyng@users.noreply.github.com "
        git config --local user.name "Robin Young"
        
    - name: Commit and Push CSV
      run: |
        git add --all        
        git commit -m "Update weather data CSV"
        git push
